version: '3.8'

services:
  web-scraper:
    build: .
    ports:
      - "5000:5000"
    environment:
      - API_KEY=${API_KEY:-your-secret-api-key}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
